# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatadogCloudResourceTagger < Formula
  desc ""
  homepage ""
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/datadog-cloud-resource-tagger/releases/download/v0.0.3/datadog-cloud-resource-tagger_Darwin_x86_64.tar.gz"
      sha256 "e17cd615e88295642d13acb4cc44183dbb77e3d691387e20f731e3deb6f49248"

      def install
        bin.install "datadog-cloud-resource-tagger"
        # Install shell completions
        generate_completions_from_executable(bin/"datadog-cloud-resource-tagger", "completion", shells: [:bash, :fish, :zsh], base_name: "datadog-cloud-resource-tagger")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DataDog/datadog-cloud-resource-tagger/releases/download/v0.0.3/datadog-cloud-resource-tagger_Darwin_arm64.tar.gz"
      sha256 "fdec41f2b103eee5c9f61f74fb9438a8c1ebcade2a0af98b9b070eda0eed2a0a"

      def install
        bin.install "datadog-cloud-resource-tagger"
        # Install shell completions
        generate_completions_from_executable(bin/"datadog-cloud-resource-tagger", "completion", shells: [:bash, :fish, :zsh], base_name: "datadog-cloud-resource-tagger")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/datadog-cloud-resource-tagger/releases/download/v0.0.3/datadog-cloud-resource-tagger_Linux_arm64.tar.gz"
      sha256 "13b3f0c82b689ef241a0349283f624f540c3d4d1ab981a1fe73dfa4af1b98fc5"

      def install
        bin.install "datadog-cloud-resource-tagger"
        # Install shell completions
        generate_completions_from_executable(bin/"datadog-cloud-resource-tagger", "completion", shells: [:bash, :fish, :zsh], base_name: "datadog-cloud-resource-tagger")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/datadog-cloud-resource-tagger/releases/download/v0.0.3/datadog-cloud-resource-tagger_Linux_x86_64.tar.gz"
      sha256 "f9dcae7a40df7b876101f791007a8e0a2e3f34fdc6d99d096a5eaa936742a202"

      def install
        bin.install "datadog-cloud-resource-tagger"
        # Install shell completions
        generate_completions_from_executable(bin/"datadog-cloud-resource-tagger", "completion", shells: [:bash, :fish, :zsh], base_name: "datadog-cloud-resource-tagger")
      end
    end
  end
end
