name: release

on:
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: .

permissions:
  contents: write
  pull-requests: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: 1.20
      - name: Run GoReleaser
        timeout-minutes: 60
        uses: goreleaser/goreleaser-action@44dd9927f499a126e26ae024981569ce889f15aa # v5.0.0
        with:
          distribution: goreleaser
          version: v1.22.1
          args: release --clean --config .goreleaser.yaml
          workdir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}