name: tests-and-linter

on: pull_request

permissions:
  contents: write

jobs:
  unit-tests:
    strategy:
      matrix:
        go: [ 1.19 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v3
      - name: Install Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go build -v && go test ./src/...
  linter:
    name: golangci-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: ./src
          only-new-issues: true
          args: --timeout=2m